### Deep Learning - Module 2 , Case study1

Install TensorFlow on your system, after installing the framework, Solve the below mentioned problem statement.

A Prime equity fund has hired you as a data scientist to analyse the data of 50 potential investee companies and create a model that will find the type of companies that he should invest in to maximize the profit.

They want to see which types of companies perform better, for eg - a company which spends on marketing or which spends more on R&D.


Task 1: Install TensorFlow on your system

→ Run a hello world command

Task 2: Train a linear regression model,

→ Train the linear regression model using training set

→ Test the created model using testing set

In [1]:
# importing tensorflow as its already installed

import tensorflow as tf

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


Task1 #Run a hello world command

In [3]:
# Create TensorFlow object called hello_constant
hello_constant = tf.constant('Hello World!')

In [4]:
sess = tf.Session()
print(sess.run(hello_constant))

b'Hello World!'


#Task 2: Train a linear regression model,

→ Train the linear regression model using training set

→ Test the created model using testing set

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [6]:
df = pd.read_csv(r'D:\E\Courses\DS_Master_Program\AI & Deep Learning with TensorFlow\Assignment\50_Startups.csv')

In [7]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [9]:
df.shape

(50, 5)

In [10]:
df.columns = df.columns.str.replace(' ', '_')

In [11]:
df.head(2)

R&D_Spend  Administration  Marketing_Spend       State     Profit
0   165349.2       136897.80        471784.10    New York  192261.83
1   162597.7       151377.59        443898.53  California  191792.06

In [12]:
df.describe()

R&D_Spend  Administration  Marketing_Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [13]:
#checking correlation between values

df.corr()

R&D_Spend  Administration  Marketing_Spend    Profit
R&D_Spend         1.000000        0.241955         0.724248  0.972900
Administration    0.241955        1.000000        -0.032154  0.200717
Marketing_Spend   0.724248       -0.032154         1.000000  0.747766
Profit            0.972900        0.200717         0.747766  1.000000

###### Profit has highest correlation with R&D spent.

In [14]:
# checking the unique of count of state values to decide if we need to include it in model creation.
df.groupby(['State']).agg({'Profit':'count'})

Profit
State             
California      17
Florida         16
New York        17

In [15]:
x = df.iloc[:,:4].values
y = df.iloc[:,4:5].values

In [16]:
print(x[:2,])

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']]


In [17]:
y[:5]

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94]])

In [18]:
# applying labelencoder to convert statte values to numbers

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,3] = le.fit_transform(x[:,3])
x[:2]

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0]], dtype=object)

In [19]:
# applying One hot encoder

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [3])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)

x = ct.fit_transform(x)

In [20]:
x[:2,:]

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53]], dtype=object)

In [21]:
# deleting extra column 

x = np.delete(x, 2, axis=1)

In [22]:
x[:2,:]

array([[0.0, 0.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 162597.7, 151377.59, 443898.53]], dtype=object)

Splitting x & y into train & test

In [23]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [24]:
len(x_train), len(x_test), len(y_train), len(y_test)

(40, 10, 40, 10)

- creating linear regression model

In [25]:
from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()
lr_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
y_pred = lr_model.predict(x_test)

In [29]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9347068473283098