### Tensor

Tensors are standard way of representing data in deep learning. Tensors are just multidimentional arrays, an extension of two-dimentional tables (matrices) to data with higher dimension.

#### Rank of tensors
Rank of Tensors define the quantity of dimension in which the tensors are live.
Rank # 0 equavalent to scalar
Rank # 1 equavalent to vector
Rank # 2 equavalent to 2D matrix
Rank # 3 equavalent to 3D matrix

### Tensorflow
Its a python library used to implement deep networks. Tensorflow code basics has 2 sections
1. Building a computational graph
2. Running a computational graph

In [3]:
#importing tensorflow

import tensorflow as tf

In [4]:
tf.__version__

'2.1.0'

### There are 3 type of data objects

- Constant  (The value will be same across the program)
- Placeholder
- Variable

In [3]:
hi_constant = tf.constant('Hello')

In [4]:
hi_constant

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello'>

In [8]:
hi_constant.get_shape()

TensorShape([])

In [11]:
hi_constant.dtype

tf.string

In [12]:
const2 = tf.constant([2,3])

In [13]:
const2.dtype

tf.int32

In [16]:
const2.get_shape()

TensorShape([2])

In [5]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [7]:
a = tf.constant(4)
b = tf.constant(6)
c = a*b
c

<tf.Tensor 'mul:0' shape=() dtype=int32>

In [8]:
tf.compat.v1.disable_eager_execution()

sess = tf.compat.v1.Session()
print(sess.run(c))
sess.close()

24


In [9]:
with tf.compat.v1.Session() as sess:

  a = tf.constant(5.0)
  b = tf.constant(6.0)
  c = tf.multiply(a, b)

  result = sess.run(c)
  print(result)

30.0


**Tensorflow Placeholders**

A placeholder is a promise to provide a value later (If we want to use a non-constant).

In [11]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

adder_node = a+b

sess = tf.Session()
sess.run(adder_node, feed_dict = {a:[1,2,3], b:[20,21,22]})

array([21., 23., 25.], dtype=float32)

In [13]:
mult_5 = adder_node*5

print(sess.run(mult_5, {a:[[1,2,3], [2,3,4], [3,2,1]], b:[[10,2,3], [2,3,4], [3,2,1]]}))

[[55. 20. 30.]
 [20. 30. 40.]
 [30. 20. 10.]]


### Tensorflow variable

Variable allow us to add trainable parameters to a graph.

y = 2 + 3*x

In [15]:
v1 = tf.Variable([5], tf.int32)

# important : need to run below code to initialize the valiable

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(v1))

[5]


In [16]:
# y = b + w*x

w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.9], tf.float32)
x = tf.placeholder(tf.float32)

linear_model = w*x + b

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(linear_model, {x:[1,2,3,4,5,7]}))

[-5.9999996e-01 -2.9999995e-01  5.9604645e-08  3.0000007e-01
  6.0000002e-01  1.2000002e+00]


### Tensorflow math

In [17]:
# tf addition

x = tf.add(5,2)

In [18]:
sess = tf.Session()
sess.run(x)

7

In [19]:
# tf substraction

y = tf.subtract(10,4)

In [21]:
y, sess.run(y)

(<tf.Tensor 'Sub:0' shape=() dtype=int32>, 6)

In [22]:
# tf multiplication

z = tf.multiply(2,5)

In [23]:
sess.run(z)

10

In [25]:
# tf matrix multiplication

m = tf.matmul([[1,5,2]], [[1],[2],[3]])

In [26]:
sess.run(m)

array([[17]])

### Converting data types

In [27]:
#we can use tf.cast to convert the datatype

In [29]:
# if we substract 1 from 2.0, it will show error

with tf.Session() as sess:
    print(sess.run(tf.subtract(tf.cast(tf.constant(2.0), tf.int32), tf.constant(1))))

1


### Tensorflow devide

In [36]:
x = tf.constant(10)
y = tf.constant(2)

z = tf.subtract(tf.divide(x,y), tf.cast(tf.constant(1), tf.float64))

with tf.Session() as sess:
    out = sess.run(z)
    print(out)

4.0


### Activation or Tramsformation functions

Activation function translates the inputs into outputs. Its uses a threshold to produce output.

Some useful activation functions in neural network
1. Linear or Identity
2. Unit or Binary step
3. Sigmoid or Logistic
4. Tanh
5. ReLU
6. Softmax


Linear: A linear transform is basically the identity function, where the dependant variable has a direst, propotional relationship with the independant variable. ie it passes the signal through unchanged. When we want to solve a Linear Regression problem, we apply Lienar Transformation function.
f(x) = x


Unit:  The output is a unit step function is either 1 or 0. It depends on the threshold value we define. When we want to solve a binary classification problem, we apply Unit Step function.
f(x) = 0 if x<0, 1 if x>= 0

Sigmoid:  Converts independant variables of near infinite range into simple probabilities between 0 and 1.
f(x) = 1/(1+e^(-beta*x))

Tanh (Tan hyperbolic): Its a hyperbolic trigonometric function. Normalized range of Tanh is -1 to +1. The advantage of Tanh is that it can deal more easily with negative numbers.

ReLU (Rectified Linear Unit): ReLU transform function only activates a node if the input is above a certain quantity. eg: While the input is below zero, the output is zero. oitput raises according to input, if input is above zero.
is Linear if inpt above a particular level.


Softmax: When we have four or five classes of outputs, the softmax function will give the probability distribution of each. It is useful for finding out the class which has the maximum probability. Softmax is the function can often find at the output layer of classifiers.

### Activation functions

In [37]:
# 1/(1+exp(-x))

import numpy as np
def sigmoid_(a):
    return 1/(1+np.exp(-a))

sigmoid_(0.3)

0.574442516811659

In [38]:
# tanh(a) = (e^a - e^-a)/(e^a + e^-a)

def tanh_(a):
    return np.tanh(a)

tanh_(0.3)

0.2913126124515909

In [39]:
def relu_(a):
    return np.maximum(0,a)

a = [-4, -2, 2,4]
for i in a:
    print(relu_(i))

0
0
2
4


In [40]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x), axis=0)

Scores = [12, 8, 0.3]
print(softmax(Scores))

[9.82005792e-01 1.79860635e-02 8.14457845e-06]


## Loss function

A loss function measures how far apart the current model is from the provided data.

### ITS AWSOME